### PR TITLE
CMake support has been added

### PR DESCRIPTION
**Pull request by Kirill71**
#1 has been resolved. I've checked these CMake files on Linux and macOS env. Everything is okay.  Also, I added some code improvements.
P.S @hrandib CMake provides a great approach to work with versioning. Let's see the file "appUtils.h.in" After CMake running in the build dir the file "appUtils.h" will be created and you will be able to get the app version, which has been declared in CMake, using AppUtils::getVersion() function.

### CODE REVIEW

**Review by hrandib — COMMENTED** [review]
Please use imperative mood in the commit subject. Also it has one typo.

**Comment by hrandib** [comment]
As I want to leave the support for both build systems this versioning approach can't be applied directly. I'll think about it.

**Comment by Kirill71** [comment]
> Please use imperative mood in the commit subject. Also it has one typo.

**Comment by Kirill71** [comment]
> > Please use imperative mood in the commit subject. Also, it has one typo.

I've fixed the commit messages.

**Pull request closed without merging**
